server:
  port: 8085

spring:
  application:
    name: notification-service

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest

      # Use ErrorHandlingDeserializer to avoid hard failures
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        # Delegate actual JSON deserialization
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        # Trust event packages (both services if needed)
        spring.json.trusted.packages: com.billing.invoiceservice.event,com.billing.notificationservice.event

        # Optional: force deserializer if type header mismatch happens
        spring.json.value.default.type: com.billing.invoiceservice.event.InvoiceCreatedEvent
